export const fields = {
    films: [
        'title',
        'release_date', 
        'director', 
        'producer', 
        {name:'characters', type:'length'},
        {name:'planets', type:'length'},
        {name:'starships', type:'length'},
        {name:'vehicles', type:'length'},
    ],
    characters: [
        'name', 
        'mass', 
        'height',
        'hair_color',
        'gender',
        'birth_year',
        'skin_color',     
        {name:'films', type:'length'},
        {name:'planets', type:'length'},
        {name:'starships', type:'length'},
        {name:'vehicles', type:'length'},
    ],
    planets:[
        'name', 
        'population', 
        'gravity',
        'diameter',
        'terrain',
        'surface_water',
        'rotation_period',     
        {name:'residents', type:'length'},
        {name:'films', type:'length'},
    ],
    starships: [
        'name', 
        'manufacturer', 
        'length',
        'hyperdrive_rating',
        'crew',
        'consumables',
        'passengers',
        'max_atmosphering_speed',
        'cargo_capacity',
        'cost_in_credits',     
        {name:'pilots', type:'length'},
        {name:'films', type:'length'},
    ],
    vehicles: [
        'name',
        'manufacturer',
        'vehicle_class', 
        'passengers',
        'max_atmosphering_speed',
        'length',
        'vehicle_class',
        'cost_in_credits',      
        {name:'pilots', type:'length'},
        {name:'films', type:'length'},,
    ],
    pilots:[
        'name', 
        'mass', 
        'height',
        'hair_color',
        'gender',
        'birth_year',
        'skin_color',     
        {name:'films', type:'length'},
        {name:'planets', type:'length'},
        {name:'starships', type:'length'},
        {name:'vehicles', type:'length'},
    ],
    residents:[
        'name', 
        'mass', 
        'height',
        'hair_color',
        'gender',
        'birth_year',
        'skin_color',     
        {name:'films', type:'length'},
        {name:'planets', type:'length'},
        {name:'starships', type:'length'},
        {name:'vehicles', type:'length'},
    ],

} 